config/routes.rb
Hunchator::Application.routes.draw do

  resources :auths do
    collection do
      get :callback
    end
  end

  resources :friends do
    member do
      get :recommend
    end
  end

end

app/models/hunch_client.rb
class HunchClient
  attr_reader :app_secret

  @@app_secret = "0f9e7e9b3e2ed7dae6d8d4a3fb246e1964723d91"

  def self.signed_get_json url
    auth_sig = get_auth_sig url, @@app_secret
    url = "#{url}&auth_sig=#{auth_sig}"
    send_get_request url
  end

  def self.get_json url
    send_get_request url
  end

  def self.send_get_request url
    begin
      response = RestClient.get url
      hash = JSON.parse(response).symbolize_keys
    rescue => e
      raise "#{e.response}"
    end
    hash
  end

  def self.enc(string)
    return string.gsub(/%20/,'+').gsub(/[+\/@]/,'+' => '%2B', '/' => '%2F', '@' => '%4O')
  end

  def self.get_auth_sig(url, app_secret)
    params = {}
    URI.parse(url).query.split('&').each do |part|
      if name = part.split('=')[0] and val = part.split('=')[1]
        params[name] = val
      else
        params[name] = ''
      end
    end

    canonical = ''
    params.sort.each do |key,val|
      canonical += key + '=' + enc(val.encode('utf-8')) + '&'
    end

    #this removes the trailing &
    canonical = canonical[0,canonical.size-1]

    string_to_sign = enc(canonical) + app_secret
    return Digest::SHA1.hexdigest(string_to_sign)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController

  require 'uri'
  require 'digest/sha1'

  APP_ID = 3149004

  HUNCH = {
    :authorize_url => "http://hunch.com/authorize/v1?app_id=#{APP_ID}&next=/auth/callback",
    :get_token_url => "http://api.hunch.com/api/v1/get-auth-token/"
  }

  def new
    redirect_to HUNCH[:authorize_url] 
  end

  def callback
    url = "#{HUNCH[:get_token_url]}?app_id=#{APP_ID}&auth_token_key=#{params[:auth_token_key]}"

    authorization = HunchClient.signed_get_json url

    session[:auth_token] = authorization[:auth_token]
    session[:user_id] = authorization[:user_id]
    session[:status] = authorization[:status]
    redirect_to friends_path(limit: 100)
  end




  

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  

  def index
    url = "http://api.hunch.com/api/v1/get-friends?auth_token=#{session[:auth_token]}&limit=#{params[:limit]}&offset=#{params[:offset]}"
    @friends = HunchClient.get_json url
  end

  def recommend
    @friend_id = params[:id]
    # session[@friend_id] = nil

    if session[@friend_id].nil?
      session[@friend_id] = {}
    end

    if session[@friend_id][:blocked_ids].nil?
      session[@friend_id][:blocked_ids] = []
    end

    if session[@friend_id][:likes].nil?
      session[@friend_id][:likes] = []
    end

    if session[@friend_id][:dislikes].nil?
      session[@friend_id][:dislikes] = []
    end

    if session[@friend_id][:offset].nil?
      session[@friend_id][:offset] = 0
    end 

    # raise "#{session[:blocked_ids]}"
    results_string = session[@friend_id][:blocked_ids].join(',')
    likes_string = session[@friend_id][:likes].join(',')
    dislikes_string = session[@friend_id][:dislikes].join(',')
    respond_to do |format|
      format.html do
        # session[@friend_id][:offset] = 0
        # url = "http://api.hunch.com/api/v1/get-recommendations?auth_token=#{session[:auth_token]}&friend_id=#{@friend_id}&topic_ids=all_394864&limit=10&offset=#{session[@friend_id][:offset]}&dislikes=#{dislikes_string}&likes=#{likes_string}&exclude_dislikes=1"
        # @recommendations = HunchClient.get_json url
        # @recommendations[:recommendations].delete_if { |r| session[@friend_id][:blocked_ids].include? r['result_id'] }
        # raise "#{session[@friend_id][:blocked_ids]}"
        # session[@friend_id][:blocked_ids] += @recommendations[:recommendations].map { |r| r['result_id'] }
        # raise "#{session[@friend_id][:blocked_ids]}"
        @recommendations = get_recommendations @friend_id, likes_string, dislikes_string
      end
      format.json do
        #session[@friend_id][:offset] += 10
        # results_blocked = (params[:blocked].split(',') + results_string.split(',')).join(',')
        results_likes = (params[:likes].split(',') + likes_string.split(',')).join(',')
        results_dislikes = (params[:dislikes].split(',') + dislikes_string.split(',')).join(',')
        #url = "http://api.hunch.com/api/v1/get-recommendations?auth_token=#{session[:auth_token]}&friend_id=#{@friend_id}&topic_ids=all_394864&limit=10&offset=#{session[@friend_id][:offset]}&dislikes=#{results_dislikes}&likes=#{results_likes}&exclude_dislikes=1"
        #puts "URL: #{url} PARAMS:"
        #@recommendations = HunchClient.get_json url

        @recommendations = get_recommendations @friend_id, likes_string, dislikes_string
        
        # session[@friend_id][:blocked_ids] += results_blocked.split(',')
        session[@friend_id][:likes] += results_likes.split(',')
        session[@friend_id][:dislikes] += results_dislikes.split(',')
        
        render json: @recommendations.to_json
      end
    end
  end

  def get_recommendations friend_id, likes_string, dislikes_string
    new_recommendations = []
    page_size = 20
    page = 0
    while new_recommendations.size < 5 do
      url = "http://api.hunch.com/api/v1/get-recommendations?auth_token=#{session[:auth_token]}&friend_id=#{friend_id}&topic_ids=all_394864&limit=#{page_size}&offset=#{page*page_size}&dislikes=#{dislikes_string}&likes=#{likes_string}&exclude_dislikes=1"
      page += 1
      recommendations = HunchClient.get_json url
      recommendations[:recommendations].each do |r|
        #puts "session[friend_id][:blocked_ids]= #{session[friend_id][:blocked_ids]}\nr['result_id']=#{r['result_id']}"
        new_recommendations << r unless session[friend_id][:blocked_ids].include? r['result_id']
      end
    end
    #raise "#{@new_recommendations}"
    session[@friend_id][:blocked_ids] += new_recommendations.map { |r| r['result_id'] }
    new_recommendations
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/auths/callback.html.erb
<%= session[:auth_token] %>

app/views/friends/index.html.erb
<% @friends[:friends].each do |friend| %>
  <%= link_to image_tag(friend["image_url"]), recommend_friend_path(friend["user_id"]), rel: 'popover', title: friend["name"] %>
<% end %>

app/views/friends/recommend.html.erb
<div id="recommendations-container" class="well">
  <% @recommendations.each do |r| %>
	  <div class="recommendation-item" rel="popover" title="<%= r['title'] %>" data-content="<%= r['description'] %>" data-item-id="<%= r['result_id'] %>">
      <div class="recommendation-item-img-div">
        <div class="actions dn">
          <a href="#" class="btn btn-success like" data-item-id="<%= r['result_id'] %>">
            <i class="icon-ok"></i>
          </a>
          <a href="#" class="btn btn-danger dislike" data-item-id="<%= r['result_id'] %>">
            <i class="icon-remove"></i>
          </a>
        </div>
        <%= link_to image_tag(r['image_url'], :class => "recommendation-item-img"), "#" %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "#", class: "more btn btn-info fr btn-large", id: @friend_id do %>
	<i class="icon-gift"></i>
	More Recommendations

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hunchator" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Giftspiration</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Authentication", new_auth_path  %></li>
              <li><%= link_to "Friends", friends_path(limit: 100, offset: 0)  %></li>
              <li><%= yield :more %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>